//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Core.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InfrastructureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfrastructureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Core.Infrastructure.InfrastructureResources", typeof(InfrastructureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account &apos;{0}&apos; is invalid..
        /// </summary>
        public static string AccountInvalid {
            get {
                return ResourceManager.GetString("AccountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration item.
        /// </summary>
        public static string ConfigurationItem {
            get {
                return ResourceManager.GetString("ConfigurationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration item &apos;{0}&apos; is specified but empty.  Using the specified default &apos;{1}&apos;..
        /// </summary>
        public static string ConfigurationItemEmptyUsingDefault {
            get {
                return ResourceManager.GetString("ConfigurationItemEmptyUsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application setting &apos;{0}&apos; is missing or has an empty value..
        /// </summary>
        public static string ConfigurationItemMissing {
            get {
                return ResourceManager.GetString("ConfigurationItemMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration item not specified - using default.
        /// </summary>
        public static string ConfigurationItemMissingUsingDefault {
            get {
                return ResourceManager.GetString("ConfigurationItemMissingUsingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron expression &apos;{0}&apos; is invalid since you cannot specify both day-of-month and day-of-week.  Specify one of the two as &apos;?&apos;..
        /// </summary>
        public static string CronBothDaysSpecified {
            get {
                return ResourceManager.GetString("CronBothDaysSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value &apos;{0}&apos; is higher than the maximum permitted value of &apos;{1}&apos;..
        /// </summary>
        public static string CronEndValueTooLarge {
            get {
                return ResourceManager.GetString("CronEndValueTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value &apos;{0}&apos; is lower than the minimum permitted value of &apos;{1}&apos;..
        /// </summary>
        public static string CronEndValueTooSmall {
            get {
                return ResourceManager.GetString("CronEndValueTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; is not valid..
        /// </summary>
        public static string CronInvalidExpression {
            get {
                return ResourceManager.GetString("CronInvalidExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CronExpression must contain exactly 5 fields.  {0} fields have specified..
        /// </summary>
        public static string CronInvalidFieldCount {
            get {
                return ResourceManager.GetString("CronInvalidFieldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification exptected candidate of type &apos;{0}&apos; but was &apos;{1}&apos;..
        /// </summary>
        public static string CronInvalidSpecificationCandidate {
            get {
                return ResourceManager.GetString("CronInvalidSpecificationCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No days specified in expression &apos;{0}&apos;.  You should not specify both day-of-month and day-of-week as &apos;?&apos;..
        /// </summary>
        public static string CronNoDaysSpecified {
            get {
                return ResourceManager.GetString("CronNoDaysSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value may not be greater than the end value..
        /// </summary>
        public static string CronStartValueLargerThanEndValue {
            get {
                return ResourceManager.GetString("CronStartValueLargerThanEndValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value &apos;{0}&apos; is higher than the maximum permitted value of &apos;{1}&apos;..
        /// </summary>
        public static string CronStartValueTooLarge {
            get {
                return ResourceManager.GetString("CronStartValueTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value &apos;{0}&apos; is lower than the minimum permitted value of &apos;{1}&apos;..
        /// </summary>
        public static string CronStartValueTooSmall {
            get {
                return ResourceManager.GetString("CronStartValueTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform operation since it will result in a duplicate &apos;{0}&apos; since there is already an entity attribute &apos;{1}&apos; with value &apos;{2}&apos;..
        /// </summary>
        public static string DuplicateEntityException {
            get {
                return ResourceManager.GetString("DuplicateEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; already exists in collection &apos;{1}&apos;..
        /// </summary>
        public static string DuplicateEntryException {
            get {
                return ResourceManager.GetString("DuplicateEntryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string with name &apos;{0}&apos; may not be empty..
        /// </summary>
        public static string EmptyStringException {
            get {
                return ResourceManager.GetString("EmptyStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering pipeline stage &apos;{0}&apos;..
        /// </summary>
        public static string EnteringPipelineStage {
            get {
                return ResourceManager.GetString("EnteringPipelineStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing pipeline &apos;{0}&apos;..
        /// </summary>
        public static string ExecutingPipeline {
            get {
                return ResourceManager.GetString("ExecutingPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First chance exception handled by pipeline: {0}.
        /// </summary>
        public static string FirstChanceExceptionHandledByPipeline {
            get {
                return ResourceManager.GetString("FirstChanceExceptionHandledByPipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTypes from assembly &apos;{0}&apos;..
        /// </summary>
        public static string GetTypesFromAssembly {
            get {
                return ResourceManager.GetString("GetTypesFromAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image encoder found for mime type &apos;{0}&apos;..
        /// </summary>
        public static string ImageEncoderNotFoundException {
            get {
                return ResourceManager.GetString("ImageEncoderNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve an implementation of an {0}..
        /// </summary>
        public static string InterfaceResolutionException {
            get {
                return ResourceManager.GetString("InterfaceResolutionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveFromTime &apos;{0}&apos; is not a valid time..
        /// </summary>
        public static string InvalidActiveFromTime {
            get {
                return ResourceManager.GetString("InvalidActiveFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveToTime &apos;{0}&apos; is not a valid time..
        /// </summary>
        public static string InvalidActiveToTime {
            get {
                return ResourceManager.GetString("InvalidActiveToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no argument with name &apos;{0}&apos;..
        /// </summary>
        public static string InvalidArgumentException {
            get {
                return ResourceManager.GetString("InvalidArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type &apos;{0}&apos; used with Guard possibly does not have a constructor that takes 1 string parameter (message).  Exception reported: {1}.
        /// </summary>
        public static string InvalidGuardExceptionType {
            get {
                return ResourceManager.GetString("InvalidGuardExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; could not be found in collection &apos;{1}&apos;..
        /// </summary>
        public static string KeyNotFoundException {
            get {
                return ResourceManager.GetString("KeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &apos;{0}&apos; with id &apos;{1}&apos; could not be located..
        /// </summary>
        public static string MissingEntityException {
            get {
                return ResourceManager.GetString("MissingEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency &apos;{0}&apos; has been accessed but it has not been set..
        /// </summary>
        public static string NullDependencyException {
            get {
                return ResourceManager.GetString("NullDependencyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value is null: {0}.
        /// </summary>
        public static string NullReferenceException {
            get {
                return ResourceManager.GetString("NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe casting from &apos;{0}&apos; to &apos;{1}&apos; resulted in a null..
        /// </summary>
        public static string NullSafeCasting {
            get {
                return ResourceManager.GetString("NullSafeCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value with name &apos;{0}&apos; may not be null..
        /// </summary>
        public static string NullValueException {
            get {
                return ResourceManager.GetString("NullValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer instance already registered against event &apos;{0}&apos;..
        /// </summary>
        public static string ObserverAlreadyRegisterAgainstEvent {
            get {
                return ResourceManager.GetString("ObserverAlreadyRegisterAgainstEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; has no extension..
        /// </summary>
        public static string PathHasNoExtensionException {
            get {
                return ResourceManager.GetString("PathHasNoExtensionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline stage &apos;{0}&apos; has no event of type &apos;{1}&apos;..
        /// </summary>
        public static string PipelineStageEventNotRegistered {
            get {
                return ResourceManager.GetString("PipelineStageEventNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no pipeline stage with a name of &apos;{0}&apos;..
        /// </summary>
        public static string PipelineStageNotFound {
            get {
                return ResourceManager.GetString("PipelineStageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raising pipeline event &apos;{0}&apos; in stage &apos;{1}&apos; for observer &apos;{2}&apos;..
        /// </summary>
        public static string RaisingPipelineEvent {
            get {
                return ResourceManager.GetString("RaisingPipelineEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range.  The from value &apos;{0}&apos; must be less than the to value &apos;{1}&apos;..
        /// </summary>
        public static string RangeException {
            get {
                return ResourceManager.GetString("RangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to assign a value to &apos;{0}&apos; but it has already been assigned a value..
        /// </summary>
        public static string ReassignmentException {
            get {
                return ResourceManager.GetString("ReassignmentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] : Stream position is not 0 but seek is not permitted..
        /// </summary>
        public static string StreamCannotSeek {
            get {
                return ResourceManager.GetString("StreamCannotSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} task pool has {1} successfully..
        /// </summary>
        public static string TaskPoolStatusChange {
            get {
                return ResourceManager.GetString("TaskPoolStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread with managed id &apos;{0}&apos; has no work and will sleep for {1} ms..
        /// </summary>
        public static string ThreadActivityWaiting {
            get {
                return ResourceManager.GetString("ThreadActivityWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue handler configuration requires thread count of at least 1.  The input queue can not be processed..
        /// </summary>
        public static string ThreadCountZeroException {
            get {
                return ResourceManager.GetString("ThreadCountZeroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread active] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string TraceProcessorThreadActive {
            get {
                return ResourceManager.GetString("TraceProcessorThreadActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread starting] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string TraceProcessorThreadStarting {
            get {
                return ResourceManager.GetString("TraceProcessorThreadStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread stopped] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string TraceProcessorThreadStopped {
            get {
                return ResourceManager.GetString("TraceProcessorThreadStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread stopping] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string TraceProcessorThreadStopping {
            get {
                return ResourceManager.GetString("TraceProcessorThreadStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception during event &apos;{0}&apos;: {1}.
        /// </summary>
        public static string UnhandledPipelineException {
            get {
                return ResourceManager.GetString("UnhandledPipelineException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static instance &apos;{0}&apos; is null.  Initialize it by calling &apos;{0}&apos; before accessing it for the first time..
        /// </summary>
        public static string UninitializedStaticInstanceException {
            get {
                return ResourceManager.GetString("UninitializedStaticInstanceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [processor thread executing] : managed thread id = {0} / processor type = {1}.
        /// </summary>
        public static string VerboseProcessorExecuting {
            get {
                return ResourceManager.GetString("VerboseProcessorExecuting", resourceCulture);
            }
        }
    }
}
