//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Core.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Core.Validation.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No control validator could be found that handles control type &apos;{0}&apos;..
        /// </summary>
        public static string ControlValidatorNotFound {
            get {
                return ResourceManager.GetString("ControlValidatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a date/time value..
        /// </summary>
        public static string DateTimeRule {
            get {
                return ResourceManager.GetString("DateTimeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a decimal value..
        /// </summary>
        public static string DecimalRule {
            get {
                return ResourceManager.GetString("DecimalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an integer value..
        /// </summary>
        public static string IntegerRule {
            get {
                return ResourceManager.GetString("IntegerRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May not be longer than {0} characters..
        /// </summary>
        public static string MaximumLengthRule {
            get {
                return ResourceManager.GetString("MaximumLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least {0} characters long..
        /// </summary>
        public static string MinimumLengthRule {
            get {
                return ResourceManager.GetString("MinimumLengthRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required..
        /// </summary>
        public static string RequiredRule {
            get {
                return ResourceManager.GetString("RequiredRule", resourceCulture);
            }
        }
    }
}
